package gui;

import dao.BarangDAO;
import javax.swing.*;
import java.util.List;

/**
 * Dashboard Admin
 * Menu utama untuk mengakses fitur manajemen ATK
 */
public class AdminDashboard extends javax.swing.JFrame {

    private BarangDAO barangDAO;
    
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents(); // Auto-generated
        setLocationRelativeTo(null);
        setTitle("Dashboard Admin - Sistem Manajemen ATK");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Inisialisasi DAO
        barangDAO = new BarangDAO();
        
        // Cek notifikasi stok menipis
        cekStokMenipis();
    }
    
    /**
     * Cek dan tampilkan notifikasi stok menipis
     */
    private void cekStokMenipis() {
        List<Object[]> stokMenipis = barangDAO.getBarangStokMenipis();
        
        if (!stokMenipis.isEmpty()) {
            StringBuilder message = new StringBuilder("PERINGATAN! Barang dengan stok menipis:\n\n");
            
            for (Object[] row : stokMenipis) {
                message.append(String.format("• %s - %s (Stok: %d, Min: %d)\n", 
                        row[0], row[1], row[3], row[5]));
            }
            
            JOptionPane.showMessageDialog(this, 
                    message.toString(), 
                    "Notifikasi Stok", 
                    JOptionPane.WARNING_MESSAGE);
        }
    }
    
    /**
     * Buka form Manajemen Barang
     * PANGGIL dari event button/menu "Kelola Barang"
     */
    private void bukaManajemenBarang() {
        new ManajemenBarangJFrameForm().setVisible(true);
        // this.dispose(); // Uncomment jika ingin tutup dashboard saat buka manajemen
    }
    
    /**
     * Logout dan kembali ke login
     * PANGGIL dari event button/menu "Logout"
     */
    private void prosesLogout() {
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Apakah Anda yakin ingin logout?", 
                "Konfirmasi Logout", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginJFrameForm().setVisible(true);
            this.dispose();
        }
    }

    /**
     * INSTRUKSI UNTUK NETBEANS GUI BUILDER:
     * 
     * 1. Tambahkan komponen di Dashboard:
     *    - JButton btnManajemenBarang → event: bukaManajemenBarang()
     *    - JButton btnLogout → event: prosesLogout()
     *    - JLabel untuk judul/header
     * 
     * 2. Set event handler:
     *    btnManajemenBarang → actionPerformed → bukaManajemenBarang()
     *    btnLogout → actionPerformed → prosesLogout()
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        // AUTO-GENERATED BY NETBEANS
        // Komponen minimal:
        // - JButton btnManajemenBarang
        // - JButton btnLogout
        // - JLabel lblTitle
    }// </editor-fold>                        

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new AdminDashboard().setVisible(true);
        });
    }

    // Variables declaration - AUTO-GENERATED                     
    private javax.swing.JButton btnManajemenBarang;
    private javax.swing.JButton btnLogout;
    // End of variables declaration                   
}