package gui;

import dao.UserDAO;
import models.Anggota;
import utils.ValidationUtils;
import javax.swing.JOptionPane;

/**
 * Form Login
 * CATATAN: initComponents() sudah auto-generated oleh NetBeans
 * Kode ini hanya menambahkan logic bisnis
 */
public class LoginForm extends javax.swing.JFrame {

    private UserDAO userDAO;
    
    /**
     * Creates new form LoginJFrameForm
     */
    public LoginForm() {
        initComponents(); // Auto-generated oleh NetBeans
        setLocationRelativeTo(null);
        setTitle("Login - Sistem Manajemen ATK");
        setResizable(false);
        
        // Inisialisasi DAO
        userDAO = new UserDAO();
        
        // Set default button (Enter = login)
        getRootPane().setDefaultButton(btnLogin);
    }
    
    /**
     * Method untuk proses login
     * PANGGIL method ini dari event handler btnLogin
     */
    private void prosesLogin() {
        // Ambil input
        String username = txtUser.getText().trim();
        String password = new String(txtPass.getPassword());
        
        // Validasi input kosong
        if (!ValidationUtils.validateRequired(username, "Username")) {
            txtUser.requestFocus();
            return;
        }
        
        if (!ValidationUtils.validateRequired(password, "Password")) {
            txtPass.requestFocus();
            return;
        }
        
        // Validasi login ke database
        Anggota user = userDAO.validateLogin(username, password);
        
        if (user != null) {
            // Login berhasil
            JOptionPane.showMessageDialog(this, 
                    "Login berhasil!\nSelamat datang, " + user.getUsername(), 
                    "Sukses", 
                    JOptionPane.INFORMATION_MESSAGE);
            
            // Buka AdminDashboard
            new AdminDashboard().setVisible(true);
            
            // Tutup form login
            this.dispose();
            
        } else {
            // Login gagal
            ValidationUtils.showError("Username atau password salah!");
            txtPass.setText("");
            txtUser.requestFocus();
        }
    }

    /**
     * INSTRUKSI UNTUK NETBEANS GUI BUILDER:
     * 
     * 1. Buka LoginJFrameForm.java dalam Design Mode
     * 2. Klik kanan btnLogin → Events → Action → actionPerformed
     * 3. Di dalam btnLoginActionPerformed, panggil method prosesLogin():
     * 
     *    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
     *        prosesLogin();
     *    }
     * 
     * ATAU jika sudah ada kode di initComponents(), cukup tambahkan listener manual:
     * 
     * Di dalam constructor setelah initComponents(), tambahkan:
     *    btnLogin.addActionListener(e -> prosesLogin());
     */
    
    // ========================================================================
    // AREA UNTUK initComponents() AUTO-GENERATED - JANGAN EDIT MANUAL!
    // Method ini akan di-generate otomatis oleh NetBeans GUI Builder
    // ========================================================================
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        // KODE INI AUTO-GENERATED OLEH NETBEANS
        // Komponen yang harus ada:
        // - txtUser (JTextField)
        // - txtPass (JPasswordField)  
        // - btnLogin (JButton)
        
        // Jika belum ada, buat menggunakan NetBeans GUI Builder!
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
           }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginJFrameForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify (AUTO-GENERATED)                     
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration                   
}